/*
NetBox REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.2.6-Docker-3.2.0 (4.2)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package netbox

import (
	"encoding/json"
	"fmt"

	"gopkg.in/validator.v2"
)

// PatchedRackReservationRequestRack - struct for PatchedRackReservationRequestRack
type PatchedRackReservationRequestRack struct {
	BriefRackRequest *BriefRackRequest
	Int32            *int32
}

// BriefRackRequestAsPatchedRackReservationRequestRack is a convenience function that returns BriefRackRequest wrapped in PatchedRackReservationRequestRack
func BriefRackRequestAsPatchedRackReservationRequestRack(v *BriefRackRequest) PatchedRackReservationRequestRack {
	return PatchedRackReservationRequestRack{
		BriefRackRequest: v,
	}
}

// int32AsPatchedRackReservationRequestRack is a convenience function that returns int32 wrapped in PatchedRackReservationRequestRack
func Int32AsPatchedRackReservationRequestRack(v *int32) PatchedRackReservationRequestRack {
	return PatchedRackReservationRequestRack{
		Int32: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *PatchedRackReservationRequestRack) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into BriefRackRequest
	err = newStrictDecoder(data).Decode(&dst.BriefRackRequest)
	if err == nil {
		jsonBriefRackRequest, _ := json.Marshal(dst.BriefRackRequest)
		if string(jsonBriefRackRequest) == "{}" { // empty struct
			dst.BriefRackRequest = nil
		} else {
			if err = validator.Validate(dst.BriefRackRequest); err != nil {
				dst.BriefRackRequest = nil
			} else {
				match++
			}
		}
	} else {
		dst.BriefRackRequest = nil
	}

	// try to unmarshal data into Int32
	err = newStrictDecoder(data).Decode(&dst.Int32)
	if err == nil {
		jsonInt32, _ := json.Marshal(dst.Int32)
		if string(jsonInt32) == "{}" { // empty struct
			dst.Int32 = nil
		} else {
			if err = validator.Validate(dst.Int32); err != nil {
				dst.Int32 = nil
			} else {
				match++
			}
		}
	} else {
		dst.Int32 = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.BriefRackRequest = nil
		dst.Int32 = nil

		return fmt.Errorf("data matches more than one schema in oneOf(PatchedRackReservationRequestRack)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(PatchedRackReservationRequestRack)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src PatchedRackReservationRequestRack) MarshalJSON() ([]byte, error) {
	if src.BriefRackRequest != nil {
		return json.Marshal(&src.BriefRackRequest)
	}

	if src.Int32 != nil {
		return json.Marshal(&src.Int32)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *PatchedRackReservationRequestRack) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.BriefRackRequest != nil {
		return obj.BriefRackRequest
	}

	if obj.Int32 != nil {
		return obj.Int32
	}

	// all schemas are nil
	return nil
}

type NullablePatchedRackReservationRequestRack struct {
	value *PatchedRackReservationRequestRack
	isSet bool
}

func (v NullablePatchedRackReservationRequestRack) Get() *PatchedRackReservationRequestRack {
	return v.value
}

func (v *NullablePatchedRackReservationRequestRack) Set(val *PatchedRackReservationRequestRack) {
	v.value = val
	v.isSet = true
}

func (v NullablePatchedRackReservationRequestRack) IsSet() bool {
	return v.isSet
}

func (v *NullablePatchedRackReservationRequestRack) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePatchedRackReservationRequestRack(val *PatchedRackReservationRequestRack) *NullablePatchedRackReservationRequestRack {
	return &NullablePatchedRackReservationRequestRack{value: val, isSet: true}
}

func (v NullablePatchedRackReservationRequestRack) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePatchedRackReservationRequestRack) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
