/*
NetBox REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.2.6-Docker-3.2.0 (4.2)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package netbox

import (
	"encoding/json"
	"fmt"

	"gopkg.in/validator.v2"
)

// ConfigContextRequestDataSource - struct for ConfigContextRequestDataSource
type ConfigContextRequestDataSource struct {
	BriefDataSourceRequest *BriefDataSourceRequest
	Int32                  *int32
}

// BriefDataSourceRequestAsConfigContextRequestDataSource is a convenience function that returns BriefDataSourceRequest wrapped in ConfigContextRequestDataSource
func BriefDataSourceRequestAsConfigContextRequestDataSource(v *BriefDataSourceRequest) ConfigContextRequestDataSource {
	return ConfigContextRequestDataSource{
		BriefDataSourceRequest: v,
	}
}

// int32AsConfigContextRequestDataSource is a convenience function that returns int32 wrapped in ConfigContextRequestDataSource
func Int32AsConfigContextRequestDataSource(v *int32) ConfigContextRequestDataSource {
	return ConfigContextRequestDataSource{
		Int32: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *ConfigContextRequestDataSource) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into BriefDataSourceRequest
	err = newStrictDecoder(data).Decode(&dst.BriefDataSourceRequest)
	if err == nil {
		jsonBriefDataSourceRequest, _ := json.Marshal(dst.BriefDataSourceRequest)
		if string(jsonBriefDataSourceRequest) == "{}" { // empty struct
			dst.BriefDataSourceRequest = nil
		} else {
			if err = validator.Validate(dst.BriefDataSourceRequest); err != nil {
				dst.BriefDataSourceRequest = nil
			} else {
				match++
			}
		}
	} else {
		dst.BriefDataSourceRequest = nil
	}

	// try to unmarshal data into Int32
	err = newStrictDecoder(data).Decode(&dst.Int32)
	if err == nil {
		jsonInt32, _ := json.Marshal(dst.Int32)
		if string(jsonInt32) == "{}" { // empty struct
			dst.Int32 = nil
		} else {
			if err = validator.Validate(dst.Int32); err != nil {
				dst.Int32 = nil
			} else {
				match++
			}
		}
	} else {
		dst.Int32 = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.BriefDataSourceRequest = nil
		dst.Int32 = nil

		return fmt.Errorf("data matches more than one schema in oneOf(ConfigContextRequestDataSource)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(ConfigContextRequestDataSource)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src ConfigContextRequestDataSource) MarshalJSON() ([]byte, error) {
	if src.BriefDataSourceRequest != nil {
		return json.Marshal(&src.BriefDataSourceRequest)
	}

	if src.Int32 != nil {
		return json.Marshal(&src.Int32)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *ConfigContextRequestDataSource) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.BriefDataSourceRequest != nil {
		return obj.BriefDataSourceRequest
	}

	if obj.Int32 != nil {
		return obj.Int32
	}

	// all schemas are nil
	return nil
}

type NullableConfigContextRequestDataSource struct {
	value *ConfigContextRequestDataSource
	isSet bool
}

func (v NullableConfigContextRequestDataSource) Get() *ConfigContextRequestDataSource {
	return v.value
}

func (v *NullableConfigContextRequestDataSource) Set(val *ConfigContextRequestDataSource) {
	v.value = val
	v.isSet = true
}

func (v NullableConfigContextRequestDataSource) IsSet() bool {
	return v.isSet
}

func (v *NullableConfigContextRequestDataSource) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConfigContextRequestDataSource(val *ConfigContextRequestDataSource) *NullableConfigContextRequestDataSource {
	return &NullableConfigContextRequestDataSource{value: val, isSet: true}
}

func (v NullableConfigContextRequestDataSource) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConfigContextRequestDataSource) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
