/*
NetBox REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.2.6-Docker-3.2.0 (4.2)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package netbox

import (
	"encoding/json"
	"fmt"

	"gopkg.in/validator.v2"
)

// FrontPortTemplateRequestRearPort - struct for FrontPortTemplateRequestRearPort
type FrontPortTemplateRequestRearPort struct {
	BriefRearPortTemplateRequest *BriefRearPortTemplateRequest
	Int32                        *int32
}

// BriefRearPortTemplateRequestAsFrontPortTemplateRequestRearPort is a convenience function that returns BriefRearPortTemplateRequest wrapped in FrontPortTemplateRequestRearPort
func BriefRearPortTemplateRequestAsFrontPortTemplateRequestRearPort(v *BriefRearPortTemplateRequest) FrontPortTemplateRequestRearPort {
	return FrontPortTemplateRequestRearPort{
		BriefRearPortTemplateRequest: v,
	}
}

// int32AsFrontPortTemplateRequestRearPort is a convenience function that returns int32 wrapped in FrontPortTemplateRequestRearPort
func Int32AsFrontPortTemplateRequestRearPort(v *int32) FrontPortTemplateRequestRearPort {
	return FrontPortTemplateRequestRearPort{
		Int32: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *FrontPortTemplateRequestRearPort) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into BriefRearPortTemplateRequest
	err = newStrictDecoder(data).Decode(&dst.BriefRearPortTemplateRequest)
	if err == nil {
		jsonBriefRearPortTemplateRequest, _ := json.Marshal(dst.BriefRearPortTemplateRequest)
		if string(jsonBriefRearPortTemplateRequest) == "{}" { // empty struct
			dst.BriefRearPortTemplateRequest = nil
		} else {
			if err = validator.Validate(dst.BriefRearPortTemplateRequest); err != nil {
				dst.BriefRearPortTemplateRequest = nil
			} else {
				match++
			}
		}
	} else {
		dst.BriefRearPortTemplateRequest = nil
	}

	// try to unmarshal data into Int32
	err = newStrictDecoder(data).Decode(&dst.Int32)
	if err == nil {
		jsonInt32, _ := json.Marshal(dst.Int32)
		if string(jsonInt32) == "{}" { // empty struct
			dst.Int32 = nil
		} else {
			if err = validator.Validate(dst.Int32); err != nil {
				dst.Int32 = nil
			} else {
				match++
			}
		}
	} else {
		dst.Int32 = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.BriefRearPortTemplateRequest = nil
		dst.Int32 = nil

		return fmt.Errorf("data matches more than one schema in oneOf(FrontPortTemplateRequestRearPort)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(FrontPortTemplateRequestRearPort)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src FrontPortTemplateRequestRearPort) MarshalJSON() ([]byte, error) {
	if src.BriefRearPortTemplateRequest != nil {
		return json.Marshal(&src.BriefRearPortTemplateRequest)
	}

	if src.Int32 != nil {
		return json.Marshal(&src.Int32)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *FrontPortTemplateRequestRearPort) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.BriefRearPortTemplateRequest != nil {
		return obj.BriefRearPortTemplateRequest
	}

	if obj.Int32 != nil {
		return obj.Int32
	}

	// all schemas are nil
	return nil
}

type NullableFrontPortTemplateRequestRearPort struct {
	value *FrontPortTemplateRequestRearPort
	isSet bool
}

func (v NullableFrontPortTemplateRequestRearPort) Get() *FrontPortTemplateRequestRearPort {
	return v.value
}

func (v *NullableFrontPortTemplateRequestRearPort) Set(val *FrontPortTemplateRequestRearPort) {
	v.value = val
	v.isSet = true
}

func (v NullableFrontPortTemplateRequestRearPort) IsSet() bool {
	return v.isSet
}

func (v *NullableFrontPortTemplateRequestRearPort) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFrontPortTemplateRequestRearPort(val *FrontPortTemplateRequestRearPort) *NullableFrontPortTemplateRequestRearPort {
	return &NullableFrontPortTemplateRequestRearPort{value: val, isSet: true}
}

func (v NullableFrontPortTemplateRequestRearPort) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFrontPortTemplateRequestRearPort) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
