/*
NetBox REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.2.6-Docker-3.2.0 (4.2)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package netbox

import (
	"encoding/json"
	"fmt"

	"gopkg.in/validator.v2"
)

// ContactRequestGroup - struct for ContactRequestGroup
type ContactRequestGroup struct {
	BriefContactGroupRequest *BriefContactGroupRequest
	Int32                    *int32
}

// BriefContactGroupRequestAsContactRequestGroup is a convenience function that returns BriefContactGroupRequest wrapped in ContactRequestGroup
func BriefContactGroupRequestAsContactRequestGroup(v *BriefContactGroupRequest) ContactRequestGroup {
	return ContactRequestGroup{
		BriefContactGroupRequest: v,
	}
}

// int32AsContactRequestGroup is a convenience function that returns int32 wrapped in ContactRequestGroup
func Int32AsContactRequestGroup(v *int32) ContactRequestGroup {
	return ContactRequestGroup{
		Int32: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *ContactRequestGroup) UnmarshalJSON(data []byte) error {
	var err error
	// this object is nullable so check if the payload is null or empty string
	if string(data) == "" || string(data) == "{}" {
		return nil
	}

	match := 0
	// try to unmarshal data into BriefContactGroupRequest
	err = newStrictDecoder(data).Decode(&dst.BriefContactGroupRequest)
	if err == nil {
		jsonBriefContactGroupRequest, _ := json.Marshal(dst.BriefContactGroupRequest)
		if string(jsonBriefContactGroupRequest) == "{}" { // empty struct
			dst.BriefContactGroupRequest = nil
		} else {
			if err = validator.Validate(dst.BriefContactGroupRequest); err != nil {
				dst.BriefContactGroupRequest = nil
			} else {
				match++
			}
		}
	} else {
		dst.BriefContactGroupRequest = nil
	}

	// try to unmarshal data into Int32
	err = newStrictDecoder(data).Decode(&dst.Int32)
	if err == nil {
		jsonInt32, _ := json.Marshal(dst.Int32)
		if string(jsonInt32) == "{}" { // empty struct
			dst.Int32 = nil
		} else {
			if err = validator.Validate(dst.Int32); err != nil {
				dst.Int32 = nil
			} else {
				match++
			}
		}
	} else {
		dst.Int32 = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.BriefContactGroupRequest = nil
		dst.Int32 = nil

		return fmt.Errorf("data matches more than one schema in oneOf(ContactRequestGroup)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(ContactRequestGroup)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src ContactRequestGroup) MarshalJSON() ([]byte, error) {
	if src.BriefContactGroupRequest != nil {
		return json.Marshal(&src.BriefContactGroupRequest)
	}

	if src.Int32 != nil {
		return json.Marshal(&src.Int32)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *ContactRequestGroup) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.BriefContactGroupRequest != nil {
		return obj.BriefContactGroupRequest
	}

	if obj.Int32 != nil {
		return obj.Int32
	}

	// all schemas are nil
	return nil
}

type NullableContactRequestGroup struct {
	value *ContactRequestGroup
	isSet bool
}

func (v NullableContactRequestGroup) Get() *ContactRequestGroup {
	return v.value
}

func (v *NullableContactRequestGroup) Set(val *ContactRequestGroup) {
	v.value = val
	v.isSet = true
}

func (v NullableContactRequestGroup) IsSet() bool {
	return v.isSet
}

func (v *NullableContactRequestGroup) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableContactRequestGroup(val *ContactRequestGroup) *NullableContactRequestGroup {
	return &NullableContactRequestGroup{value: val, isSet: true}
}

func (v NullableContactRequestGroup) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableContactRequestGroup) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
